- name: "Continuar parchado"
  hosts: all
  gather_facts: true
  order: sorted
  vars: 
    aix_reports_path: /tmp
  tasks:
  - name: "Definir hechos "
    ansible.builtin.set_fact:
      aix_report_post_patch: "{{ ansible_hostname }}_{{ ansible_date_time.date }}_{{ ansible_date_time.hour  }}{{ ansible_date_time.minute }}{{ ansible_date_time.second  }}_{{ tower_job_id }}_POST.txt"
  
  - name: "Tomar evidencias previas al parchado"
    ansible.builtin.include_tasks:
      file: generar_status_aix.yaml
    vars:
      aix_report_file: "{{ aix_report_post_patch }}"
      
  - name: "Comparar informacion de reportes pre y post patching "
    ansible.builtin.shell: >-
      diff "{{ aix_report_pre_patch }}"  "{{ aix_report_post_patch }}"
    args:
      chdir: "{{ aix_reports_path }}"
    register: registro_aix_comparar_reportes
    failed_when: registro_aix_comparar_reportes.rc > 1
    changed_when: registro_aix_comparar_reportes.rc == 1
    
  - name: "Comparar informacion de reportes pre y post patching - Resultado"
    ansible.builtin.debug:
      msg: "{{ registro_aix_comparar_reportes.stdout_lines }}" 
