- name: "Print Dict"
  hosts: localhost
  gather_facts: false
  vars:
    projects:
      pagos:
        dc1: orqpagos1002
      clientes:
        dc1: wsclientes0169
      prueba:
        dc1: podprueba
  tasks:
      - name: "Print variables"
        ansible.builtin.debug:
          msg: "Project {{ item.key }} has {{ item.value.dc1 }})"
        loop: "{{ lookup('ansible.builtin.dict', projects) }}"
