- name: "Prueba"
  hosts: all
  gather_facts: true
  vars: 
    aix_reports_path: /tmp
    
  tasks:

  - name: Create file /tmp/hola with content "Hello World"
    ansible.builtin.copy:
      content: hello world
      dest: /tmp/hola

  - name: Umount FS
    mount:
      path: /
      state: unmounted
    ignore_errors: true
    register: umount_result

  - debug:
      msg: "El FS bk_mksysb no se monto"
    when: umount_result.rc != 0






    


