- name: "Create file"
  hosts: all
  gather_facts: false
  tasks:
      - name: "Creacion del archivo db_encendida"
        ansible.builtin.copy:
          content: '1'
          dest: "/tmp/encendida"
